---
- name: Upgrade Service Catalog
  hosts: oo_first_master
  vars:
    first_master: "{{ groups.oo_first_master[0] }}"
  tasks:
  - import_role:
      name: openshift_service_catalog
      tasks_from: install.yml
    when:
    - openshift_enable_service_catalog | default(true) | bool
  - import_role:
      name: ansible_service_broker
      tasks_from: install.yml
    when:
    - openshift_enable_service_catalog | default(true) | bool
  - import_role:
      name: template_service_broker
      tasks_from: upgrade.yml
    when:
    - openshift_enable_service_catalog | default(true) | bool

# Label rest of master nodes - will be a no-op if only one master exists
- name: Ensure all masters are labeled with node selector for Service Catalog
  hosts: oo_masters_to_config
  tasks:
  - name: Label {{ openshift.node.nodename }} for APIServer and controller deployment
    oc_label:
      name: "{{ openshift.node.nodename }}"
      kind: node
      state: add
      labels: "{{ openshift_service_catalog_nodeselector | default ({'openshift-infra': 'apiserver'}) | lib_utils_oo_dict_to_list_of_dict }}"
